name: Build, Test, and Release

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run tests
        run: cargo test --verbose

  build-linux:
    name: Build for Linux (x86_64)
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-gnu
      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: minesweeper_ng_gen
          path: target/x86_64-unknown-linux-gnu/release/

  build-windows:
    name: Build for Windows (x86_64)
    runs-on: windows-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true
      - name: Build
        run: cargo build --release --target x86_64-pc-windows-msvc
      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: minesweeper_ng_gen.exe
          path: target/x86_64-pc-windows-msvc/release/

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          
      - uses: ncipollo/release-action@v1
        with:
          tag: "v0.8.0"
          name: "Minesweeper NG Generator"
          body: "Manual Release"
          artifacts: "dist/**"
          token: ${{ secrets.GITHUB_TOKEN }}
